//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHub.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameHub.Application.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not found..
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not found or does not belong to user..
        /// </summary>
        public static string AddressNotFoundOrDoesNotBelong {
            get {
                return ResourceManager.GetString("AddressNotFoundOrDoesNotBelong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your account has been blocked..
        /// </summary>
        public static string AccountBlocked {
            get {
                return ResourceManager.GetString("AccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shopping cart is empty..
        /// </summary>
        public static string CartEmpty {
            get {
                return ResourceManager.GetString("CartEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to perform this action..
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The request was invalid..
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cloudinary configuration is missing. Please set Cloudinary:CloudName, Cloudinary:ApiKey and Cloudinary:ApiSecret (or CloudinarySettings:CloudName/ApiKey/ApiSecret) in configuration..
        /// </summary>
        public static string CloudinaryConfigurationMissing {
            get {
                return ResourceManager.GetString("CloudinaryConfigurationMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cloudinary upload failed: {0}.
        /// </summary>
        public static string CloudinaryUploadFailed {
            get {
                return ResourceManager.GetString("CloudinaryUploadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to access database connection..
        /// </summary>
        public static string DatabaseConnectionUnavailable {
            get {
                return ResourceManager.GetString("DatabaseConnectionUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card detail not found..
        /// </summary>
        public static string CardDetailNotFound {
            get {
                return ResourceManager.GetString("CardDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game &apos;{0}&apos; is no longer available..
        /// </summary>
        public static string GameNoLongerAvailable {
            get {
                return ResourceManager.GetString("GameNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not found..
        /// </summary>
        public static string GameNotFound {
            get {
                return ResourceManager.GetString("GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game with id {0} not found..
        /// </summary>
        public static string GameNotFoundById {
            get {
                return ResourceManager.GetString("GameNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is out of stock..
        /// </summary>
        public static string GameOutOfStock {
            get {
                return ResourceManager.GetString("GameOutOfStock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email already registered..
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient stock for product: {0}..
        /// </summary>
        public static string InsufficientStock {
            get {
                return ResourceManager.GetString("InsufficientStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be at least {0}..
        /// </summary>
        public static string InvalidQuantity {
            get {
                return ResourceManager.GetString("InvalidQuantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid id. Use a numeric user id, e.g. /api/admin/AdminUsers/1.
        /// </summary>
        public static string InvalidAdminUserId {
            get {
                return ResourceManager.GetString("InvalidAdminUserId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid order status. Allowed values: Pending, Placed, Processing, Shipped, Delivered, Cancelled..
        /// </summary>
        public static string InvalidOrderStatus {
            get {
                return ResourceManager.GetString("InvalidOrderStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid role. Allowed values: Admin or User..
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found in wishlist..
        /// </summary>
        public static string ItemNotFoundInWishlist {
            get {
                return ResourceManager.GetString("ItemNotFoundInWishlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order not found..
        /// </summary>
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested product could not be found..
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh token is required..
        /// </summary>
        public static string RefreshTokenRequired {
            get {
                return ResourceManager.GetString("RefreshTokenRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired refresh token..
        /// </summary>
        public static string InvalidOrExpiredRefreshToken {
            get {
                return ResourceManager.GetString("InvalidOrExpiredRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please login again..
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the given credentials already exists..
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
